# Generated by Django 6.1.1 on 2026-09-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Corretores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno')], max_length=20)),
                ('finalidade', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('cidade', models.CharField(max_length=100)),
                ('quartos', models.PositiveIntegerField(default=0, verbose_name='quartos')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='imoveis.corretor', verbose_name='corretor responsável')),
            ],
            options={
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
